### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by ghost** [remymuller/juce-cmake#11]
Hello Remy!

Would you mind adding a license to this repository? Otherwise it’s impossible to use this repo in other projects. MIT license or something similar would be awesome.

Thanks!

**Comment by FlorianFranzen** [comment]
I would love to see if I could get [open-ephys/plugin-GUI](https://github.com/open-ephys/plugin-GUI) to build in cmake with the help of this module, however I would need to know how the code is licensed first.

The templates seem to be covered under the "JUCE 5 End-Use License Agreement", but what about the code you wrote and published here?

**Comment by remymuller** [comment]
juce-cmake is now licensed under the MIT.
